### ISSUE TITLE
Syntax error when running `cimg init`

### ISSUE THREAD

**Issue by croissanne** [allisonkarlitskaya/cimg#6]
```
Traceback (most recent call last):
  File "/home/sanne/.local/bin/cimg", line 11, in <module>
    import image_download
  File "/home/sanne/workstuff/cimg/image_download.py", line 64
    while block := work_queue.get():
                 ^
SyntaxError: invalid syntax

```

**Comment by allisonkarlitskaya** [comment]
https://www.python.org/dev/peps/pep-0572/ says assignment expressions are only supported since Python 3.8.
